plugin/chatgpt.lua

Hi, thank you so much for an amazing plugin!
One issue I have is that since the code `require("chatgpt")` in a file inside `plugin/`, this plugin is required during setup.
This prevents the possibility of lazy loading this plugin.
This PR is a quick fix to this problem which requires the plugin inside an anonymous function.
I created a script to ask for an `OPENAI_API_KEY` via `vim.ui.input` if none is specified as an environment variable. This does not work if the plugin checks for an environment variable on startup.
```lua
use({
"jackMort/ChatGPT.nvim",
config = function()
local function setup_chatgpt()
require("chatgpt").setup({
})
end
if string.len(vim.env.OPENAI_API_KEY or "") < 1 then
vim.notify(string.format("$OPENAI_API_KEY not set: %s", vim.env.OPENAI_API_KEY or "nil"), …
```

bug: The plugin cannot lazy load

---

lua/chatgpt/flows/actions/completions/init.lua
lua/chatgpt/flows/actions/edits/init.lua
lua/chatgpt/flows/actions/init.lua

Hi Lech
These might be useful for you.  There are 2 commits. The first implements functional openai edit api calls, and the second accommodates the openAI completion `insert` api.  It does the latter by taking care of splitting the input prompt into `prompt` and `suffix` chunks at the [insert] token, and implementing specialised `append` and `prepend` replacement strategies.  
My lua is pretty rusty, so I am sure you could do it more beautifully. Feel free to reject any or all of it.  Your code was easy to work with, very logical, you have a good mind for coding.

Code to modularise the openAI calls

---

README.md
lua/chatgpt/config.lua
lua/chatgpt/flows/chat/sessions.lua

Hi!
I added some options to rebind mappings for the session pane - specifically I wanted to rebind the "select_session" one since I have a conflict with <Space>, but added the others. Plus having them documented in the README is a bonus too!
PS. Thanks for this plugin - very cool!

feat(keymaps): allow rebinding sessions pane mappings

---

lua/chatgpt/code_edits.lua
lua/chatgpt/flows/actions/edits/init.lua
lua/chatgpt/utils.lua

The following is from my personal fork to improve editing (interactively or via actions) of visual selections; maybe it's interesting for main? In any case, thanks for the great plugin :).
Currently, if a visual selection is edited (either interactively or via an edit action), an unwanted newline was inserted. This pull request avoids such newlines.
The changes (a) ensure that the visual selection is yanked/pasted without creating additional newlines and (b) enforce that ChatGPT's answer ends in exactly as many newlines as the visual selection. The latter is necessary since ChatGPT seems to always add a newline at the end of its answer, even if the input did not contain one. Note that this might be considered a downside of the pull request, since requests like `add 3 newlines at the end` …

Improved newline handling in interactive code edits and edit actions

---

lua/chatgpt/code_edits.lua
lua/chatgpt/module.lua

Only `cycle_windows` when the settings are open by checking `settings_open` boolean.
This resolves https://github.com/jackMort/ChatGPT.nvim/issues/34

Fix `cycle_windows` when settings are closed

---

lua/chatgpt/module.lua
lua/chatgpt/utils.lua

Hi.
Your plugin is my co-pilot when I code.
Thanks for the very cool plugin.
Now, for my use case, I wanted to partially copy the answer from chatGPT, so I made this change.
This change includes the following changes, but only adopt what you like.
change point:
- Changed not to move with cycle panes feature when settings panel does not exist
- Changed to switch to normal mode when settings panel is opened
- Added chat window as destination for cycle panes feature

feat(cycle panes): move to chat window using cycle panes

---

lua/chatgpt/module.lua

When computing amount to scroll, `math.abs` should be `math.floor` to prevent fractional values.
Resolves https://github.com/jackMort/ChatGPT.nvim/issues/126

Fix `<C-u>` and `<C-d` scrolling for specific window sizes

---

lua/chatgpt/module.lua
lua/chatgpt/utils.lua

Currently, if the input text is too long, it is hidden under the tokens/price indicator, see #66.
This PR hides the tokens/price indicator when it would overlap with the input text:
The tokens/price indicator is visible for short inputs.
When the line length gets too long, the indicator disappears.
The indicator reappears if the line length again becomes short enough.
Note that this PR does not target the second issue in #66 as I didn't observe it in my testing. The tokens/price indicator always shows on the line after the output text:

fix: Hide tokens price if it covers the input text

---

README.md
lua/chatgpt/config.lua
lua/chatgpt/prompts.lua

To utilize CSV files other than 'awesome-chatgpt-prompts' for testing new prompts or using a customized version, the 'config.lua' file includes an option called 'predefined_chat_gpt_prompts'. This option enables the user to set their own URL instead of the previously hardcoded one.
The provided URL must adhere to the CSV file format of 'awesome-chatgpt-prompts'.

feat: enable configuration of predefined chatgpt prompts.

---

lua/chatgpt/module.lua

I have made a change to assign a "close window" keymap to all windows that appear with the ChatGPT command.
This change seems to be related to the following issue and pull request.
issue #164 
pull request #139 
If you respect pull request #139, you can cancel the addition of keymaps to insert mode.
```lua
-- close
for _, popup in ipairs({ settings_panel, sessions_panel, chat_input, chat_window }) do
local close_keymaps = Config.options.chat.keymaps.close
if type(close_keymaps) ~= "table" then
close_keymaps = { close_keymaps }
end
for _, keymap in ipairs(close_keymaps) do
-- popup:map("i", keymap, function()
--   chat_input.input_props.on_close()
-- end, { noremap = true, silent = true })
popup:map("n", keymap, function()
chat_input.input_props.on_close()
end, { noremap = true, silent = …
```

add close keymap to all window in ChatGPT command (#164)

---

lua/chatgpt/settings.lua

Applying the same fix as 'reading settings'.  The filename is resolved to 'HOME' directory so it will cause an error when trying to save settings.

Fixing settings saving. The filename is not properly created

---

CHANGELOG.md
README.md
lua/chatgpt.lua
lua/chatgpt/api.lua
lua/chatgpt/config.lua

This PR adds a feature to the plugin that introduces an alternative method of providing the OpenAI API key. In addition to providing the key via an `OPENAI_API_KEY` environment variable, the plugin also supports getting the API key from the output of arbitrary commands, configured via the `api_key_cmd` configuration parameter.
This allows users to securely provide the API key, without having to write it in clear-text to disk. It also prevents the API key from being readable by processes with access to the initial environment variables of neovim.
The default behaviour is to use the `OPENAI_API_KEY` environment variable, so as to not break backwards compatibility.
The README includes a couple of examples of how to use `op` or `gpg` to inject the secret into neovim.
Disclaimer: This is my …

feat(api): added api_key_cmd configuration option

---

lua/chatgpt/api.lua

fixes jackMort/ChatGPT.nvim#184 by guaranteeing no whitespace is to be at the end of the key string.

fix Windows adding whitespace at the end of the key

---

lua/chatgpt/api.lua
lua/chatgpt/common/logger.lua

Hi! There is some incorrect if statement logic in the new `api_key_cmd` setup that results in this nasty-looking error on startup in environments without an API key (this can happen in a variety of situations like editing your [kitty](https://github.com/kovidgoyal/kitty) settings in this example screenshot)
This pr fixes the if statement logic, and switches to a more pleasant warning if this kind of thing ever happens:

fix(api): warn instead of crash in unconfigured environments

---

README.md
lua/chatgpt/api.lua

The setup option of `api_key_cmd` is great, but it's performed synchronously. As I use a password store backed by a Yubikey, this can cause a significant delay when opening up Neovim.
In order to solve this, I've added a new setup option of `async_api_key_cmd` which uses plenary.job to asynchronously load the API key. For me, this improves the performance of opening up neovim and makes the plugin usable again. 
There are some caveats with this, however.
You can only specify a command that follows the following format:
```
<cmd> <args>
```
Anything with piping, won't work. i.e.
```
<cmd> <args> | <cmd2>
```
Therefore, I opted to add a new setup configuration value, to ensure this does not break existing configurations. There may be a way to improve on this so that any command can be …

Add in a new setup option for asynchronously loading API key

---

README.md
lua/chatgpt/config.lua
lua/chatgpt/input.lua

This pull request introduces a fix for the issue where long prompts would overflow the screen. By limiting the number of visible lines in the input popup, we prevent overflow and ensure that the user interface remains clean and accessible. This enhancement improves the overall user experience, particularly when dealing with large amounts of text. It is configurable so users will be able to choose if this feature is enabled.

Limit Visible Lines in Input Popup

---

README.md
lua/chatgpt/api.lua

In some countries, it is too hard to accessing OpenAI. So they can deploy it's own reverse proxy server to access openai API

feat(api): support custom api host

---

lua/chatgpt/api.lua

Hello!
The changes regarding the addition of alternative APIs are simply amazing!
But as far as I understand, the function that checks OPENAI_API_HOST should also trigger a callback if this variable exist
for the subsequent determination of COMPLETIONS_URL, CHAT_COMPLETIONS_URL, and EDITS_URL.
It should resolve https://github.com/jackMort/ChatGPT.nvim/issues/265

Simple way to fix error "curl: no URL specified"

---

plugin/chatgpt.lua

I think this may have been accidentally closed: https://github.com/jackMort/ChatGPT.nvim/pull/58
This allows visual linewise selection and function call without any obvious downside.

fix: permit ChatGPTEditWithInstructions to work with visual linewise selection

---

lua/chatgpt/api.lua
lua/chatgpt/code_edits.lua
lua/chatgpt/config.lua
lua/chatgpt/utils.lua

This is a *mostly* working solution, which greatly expands upon the work started at https://github.com/jackMort/ChatGPT.nvim/pull/249
This PR implements a cleaner version of using GPT 3.5/4 directly, and also has support for leveraging OpenAI functions if the `use_openai_functions_for_edits` config option is set to `true` (default is `false`).
On the whole, using OpenAI functions works well, however, there are some edge cases where parsing out the function arguments throws JSON parsing errors -- I tried for awhile to figure out the escaping magic to get it to behave in all cases, but so far have not had luck. Perhaps another set of eyes could help with that...

Edit with instructions using OpenAI functions

---

README.md

Discovered that you can't use spaces inside arguments passed to `api_key_cmd` since the job command is splitting arguments on whitespace.
Added it as a note to the README in an attempt to save the next person the 10 minutes of debugging it took me to figure this out.
Checked the preview of the readme. Otherwise rely on spell checking.

Add note to README about api_key_cmd and spaces

---

lua/chatgpt/code_edits.lua
lua/chatgpt/config.lua
lua/chatgpt/flows/actions/base.lua
lua/chatgpt/flows/chat/base.lua
lua/chatgpt/flows/chat/sessions.lua
lua/chatgpt/settings.lua

These new config options will resolve #187 by allowing users to change all of the nerd font icons. It is an alternative to #295 that maintains backwards compatibility for people still using old versions of the patched fonts.
Let me know if I missed any icons, or if you would prefer different names for the config options. Thanks!

feat: add config options to replace all nerd font icons

---

README.md
lua/chatgpt/api.lua

By setting several environment variables, this change allows the use of OpenAI service provided by Azure. It might solve #212.

feat: add support for Azure OpenAI deployment

---

lua/chatgpt/api.lua

curl: option -H: requires parameter error
Seems to be related to this change here from this PR that tries to add support for AZURE environment variables as well.
https://github.com/jackMort/ChatGPT.nvim/pull/293/files
Api.AUTHORIZATION_HEADER is nil in Api.chat_completions...
The callback passed to loadApiKey is not guaranteed to be called in the case that the environment variable for OPENAI_API_KEY exists.
```lua
local function loadConfigFromEnv(envName, configName)
local variable = os.getenv(envName)
if not variable then
return
end
Api[configName] = variable:gsub("%s+$", "")
end
-- ...
local function loadApiKey(envName, configName, optionName, callback, defaultValue)
loadConfigFromEnv(envName, configName)
if not Api[configName] then
if Config.options[optionName] ~= nil and …
```

Fix #303: curl error

---

lua/chatgpt/api.lua

In order to use local tools that offer an Open AI compatible API (I'm using litellm) without messing around with certificates, I needed to add `http` support to this plugin.
I've done this without breaking any existing behavior. The change detects if the `OPENAI_API_HOST` value starts with either `http://` or `https://`, if it starts with neither, it will automatically add `https://` to the beginning of the URL as before. Otherwise it leaves the URL as is.
I took this approach for two reasons:
1. No breaking change; if this change doesn't concern you, you won't notice it.
2. Security - if the url doesn't have the protocol specified, defaulting to https will ensure there are no accidental unsecured connections.
Thanks for all the work on this project and thanks for your consideration.

Enables dynamic support for `http` and `https` OPENAI_API_HOSTs 

---

lua/chatgpt/flows/chat/base.lua

[vision.webm](https://github.com/jackMort/ChatGPT.nvim/assets/61915524/7d568f01-fadf-4775-a516-4daaff48f99e)
Added support for gpt-4-vision-preview.
If you're interested here's the plugin I wrote to get the image from the clipboard to cloudinary ;)
https://github.com/e2r2fx/cloudy.nvim
Another possible feature is to add image previews with [image.nvim](https://github.com/3rd/image.nvim) to the chat window

feat(chat): enable support for gpt 4 vision api

---

lua/chatgpt/flows/chat/base.lua

When the border style is set to "none", the input box unexpectedly gains an additional margin. Here are the screenshots illustrating the issue:
I fix this issue by setting the input box margin to zero when the border is none.

Remove margin from input window when border style is 'none'.

---

lua/chatgpt/code_edits.lua

It will now keep wrap=True in diffmode instead of too long invisible lines, which is more readable now

Make diff mode more readable.

---

README.md

Addresses
https://github.com/jackMort/ChatGPT.nvim/commit/f1453f588eb47e49e57fa34ac1776b795d71e2f1
https://github.com/jackMort/ChatGPT.nvim/issues/263
Though I noticed that section of the README still contains duplicate keybinds. Unsure whether that is actionable.

fix: update draft keybind to match #f1453f5

---

README.md
lua/chatgpt/api.lua
lua/chatgpt/config.lua

Good day!
Since the official API is not accessible in my country, I must rely on third-party alternatives.
Some of them require the inclusion of specific request headers, such as 'Origin' and 'Referrer.'
The modifications in this pull request enable the specification of these headers without causing any breaking changes.
I have also added a description of usage in the README.

Add the ability to use additional parameters in requests

---

lua/chatgpt/flows/actions/init.lua

Whenever the user inputs a invalid action, indicate the action does not exist, and show a list of the available actions.
Before:
After:

Handle invalid action

---

README.md

To correctly execute the command:
```
ChatGPTRun code_readability_analysis
```
It is necessary to have the "trouble.nvim" plugin.
Otherwise you get the nvim error saying:
```
Vim:E492: Not an editor command: Trouble quickfix
```
This commit makes it explicit in the README that trouble plugin is a dependency.
The `trouble` dependency is here: 
https://github.com/jackMort/ChatGPT.nvim/blob/48c59167beeb6ee0caa501c46cecc97b9be8571d/lua/chatgpt/config.lua#L176

List in README "folke/trouble.nvim" as dependency

---

lua/chatgpt/help.lua

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```
```
Error executing Lua callback: ....local/share/nvim/lazy/ChatGPT.nvim/lua/chatgpt/help.lua:43: attempt to concatenate a table value                                                                                                                                                                                                                                          
stack traceback: …
```

fix: Failed to launch in neovim 0.9.5 #371

---

lua/chatgpt/code_edits.lua

This Fixes https://github.com/jackMort/ChatGPT.nvim/issues/352
Closes #352
Something in 1f69ba2 broke this - here's a fix for it.
For some reason the active_panel is coming up nil when the view initially opens. It's being set at the top, but something is overwriting it.

Fix issue with cycling panes in edit_with_instructions

---

lua/chatgpt/code_edits.lua
lua/chatgpt/config.lua

Addresses #234 
- add 'show_line_numbers = true' to default config
- add check in code_edits.lua before setting the line numbers for the window
- setting 'show_line_numbers = false' will disable the line numbers
when setting show_line_numbers = false, it would be advisable to also set the popup_window.win_options.foldcolumn = "0", to get clean experience, but I left that option for the users.

feat: add option to set nonumber for popup windows

---

README.md
lua/chatgpt/api.lua

Due to asynchronous operations, loading the *_cmd options for Azure from the vim configuration was not working correctly. It only worked using the environment variables.
This also adds a missing option to set the API type (api_type_cmd) from the vim configuration files instead of having to set an environment variable.
Fixes #365

fix(api): fix issue loading Azure OpenAI configuration

---

lua/chatgpt/api.lua

add param to [vim.json.decode](https://neovim.io/doc/user/lua.html#vim.json) , converts null in JSON objects to Lua nil instead of [vim.NIL](https://neovim.io/doc/user/lua.html#vim.NIL)
Because:
```lua
if vim.NIL then
-- The following code will execute
print("hello");
end
```

[bug fix] Fix the code error when there is a null value in the json returned by the api

---

README.md
lua/chatgpt/api.lua
lua/chatgpt/code_edits.lua
lua/chatgpt/flows/chat/base.lua
lua/chatgpt/settings.lua
lua/chatgpt/utils.lua

Earlier this day, I raised an issue here: https://github.com/jackMort/ChatGPT.nvim/issues/414
Then, I decided to dive into the codebase and add the feature myself using my proposed change.
openai_params.model can now be either a constant string (only method so far) or **a function that returns a string containing the model** (new). The model is thus computed on the fly when an API request is made.
So far, without this change, it has not been possible to change the model you are using on the fly. With the modifications this PR introduces, one can now pass a function instead of a fixed model, and the function returns the model to be used. This function is evaluated on API invokation.
- add a Utils.collapse_openai_params function to, if the openai_params.model parameter is a function, …

Change model on the fly

---

README.md
lua/chatgpt/flows/actions/base.lua
lua/chatgpt/flows/actions/chat/init.lua

Currently, action templates support the following variables: {{filetype}} (neovim filetype), {{input}} (the selected text) and an {{argument}} (provided on the command line). 
During an exploration in writing tests with LLMs, I found that providing the path to the file relative to the root of my project allowed my LLM to properly import the file to write the tests for it.
So I contributed `{{filepath}}`, a new variable which gets the relative path to the file being operated on.
This was done by adding a new method `get_filepath` to `BaseAction` and adding the `filepath` variable to `render_template`. 
I tested this by writing a template with `{{filepath}}` and observing the path getting put into the prompt with this OpenAI compatible API …

Add `filepath` to action variables

---

lua/chatgpt/code_edits.lua

feat: Add support for ChatGPT 4 in code edits.

---

README.md

Thanks to maintaining great neovim plugin!
I added missing code block separator in `README.md`.

docs: add missing code block separator in `README.md`

---

lua/chatgpt.lua
lua/chatgpt/code_edits.lua
lua/chatgpt/common/preview_window.lua
lua/chatgpt/config.lua
lua/chatgpt/flows/actions/init.lua
lua/chatgpt/flows/chat/base.lua
lua/chatgpt/flows/chat/init.lua
lua/chatgpt/module.lua
lua/chatgpt/utils.lua

1. Calling Signs.set_for_lines with a busy call will cause neovim to freeze.
2. Resolved chat window unmodifiable error and avoid streaming response clearing on panel redraw.
1. Support setting a separate close window keymap in normal mode.
3. Support opening the chat window with options, which is useful when carrying selected content into the chat window.
4. Allow ignoring the default action path, as the default actions.json specifies models. This option provides a way for users to customize actions with the same content when those specified models are not needed.
5. Support a default system message.

Fixed 2 issues and added 5 features

---

lua/chatgpt/config.lua

An attempt at making trouble optiona. 
@jackMort  What do you think about this approach? If it's alright I can fix the docs as well. 
Disclaimer: Couldn't test this since I don't have  an openai user anymore

feat: Make trouble.nvim optional
